name: 'Apply planned settings'
on:  
  pull_request_review:
    types: [submitted]


env:
  tf_version: 'latest'
  tg_version: 'latest'
  tf_working_dir: './CVT-IaC-Live-AZURE/ci-prod/ci-prod-vnet/'
  STORAGE_KEY: ${{secrets.STORAGE_KEY}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  generate-matrix:
      if: github.event.review.state == 'approved'
      name: 'PORISAK'
      runs-on: ubuntu-latest

      steps:

        - uses: actions/checkout@v3
        - name: Debugsss
          run: |
            echo Hello-WORLD!!
#